import { VacancyInsert } from '@jobly/db/src/schema'

// Type to make all optional fields required
// Made to not miss any insert columns
type StrictifyNullable<T> = {
  [K in keyof T]-?: null extends T[K] ? Exclude<T[K], undefined> | null : Exclude<T[K], undefined>
}

// Type for which all columns of vacancy table are required
// 'id' and 'createdAt' are auto generated by drizzle, no point of checking type, so making them any
export type VacancyInsertStrict = Omit<StrictifyNullable<VacancyInsert>, 'id' | 'createdAt'>
